# Generated by Django 4.2.10 on 2024-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=100, null=True)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('saddress', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
